routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/* REGISTER/LOGIN */
Auth::routes();
Route::get('{provider}', 'AuthSocialController@redirect')->where('provider', '(facebook|google)');
Route::get('{provider}/callback', 'AuthSocialController@callback')->where('provider', '(facebook|google)');
Route::get('/changePassword', 'HomeController@showChangePasswordForm');
Route::post('/changePassword', 'HomeController@changePassword')->name('changePassword');
Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser')->name('verify.user');
// Route::get('/verify/resend/', 'Auth\LoginController@verifyAccountReSendEmail')->name('verify.user.resend');

/* DASHBOARD */
Route::get('/home', 'HomeController@index')->name('home');

/* CONTACT */
Route::get('/contact', 'ContactController@show')->name('contact');
Route::post('/contact/send', 'ContactController@send')->name('contact.send');

/* USER */
Route::resource('/user', 'UserController');

/* NETWORK */
Route::get('/network/{slug}/Addfriend', 'NetworkController@getAdd')->name('addFriend');
Route::get('/network/{slug}/Acceptfriend', 'NetworkController@getAccept')->name('Acceptfriend');
Route::get('/network/search', 'NetworkController@searchcontact')->name('network.search');
Route::get('/network/{slug}/invitations', 'NetworkController@invitations');
Route::get('network/{slug}/delete', ['uses' => 'NetworkController@destroy', 'as' => 'network.delete']);
Route::post('network/search/result', 'NetworkController@search')->name('network.search.result');
Route::resource('/network', 'NetworkController');

/* BLOG */
Route::resource('/blog', 'BlogController');

/* WORKSHOP */
Route::resource('/workshop', 'WorkshopController');

/* ADVICE SHEET */
Route::resource('/sheet', 'AdviceSheetController');
Route::get('/sheet/pdf/{id}', 'AdviceSheetController@pdf')->name('sheet.pdf');

/* NOTIFICATIONS */
Route::resource('/notifications', 'NotificationsController');

/* CHILDCARE */
Route::get('/childcare/acceptchildcare/{id}', 'ChildcareController@acceptChildcare')->name('childcare.accept');
Route::get('/childcare/confirmchildcare/{id}', 'ChildcareController@confirmChildcare')->name('childcare.confirm');
Route::get('/childcare/refusechildcare/{id}', 'ChildcareController@refuseChildcare')->name('childcare.refuse');
Route::get('/childcare/refuse/{id}', 'ChildcareController@refuse')->name('childcare.refused');
Route::get('childcare/{id}/delete', ['uses' => 'ChildcareController@destroy', 'as' => 'childcare.delete']);
Route::get('/childcare/networkneeds', 'ChildcareController@networkNeeds')->name('childcare.networkneeds');
Route::get('/childcare/myneeds', 'ChildcareController@myNeeds')->name('childcare.myneeds');
Route::get('/childcare/mychildcares', 'ChildcareController@myChildcares')->name('childcare.mychildcares');
Route::resource('/childcare', 'ChildcareController');

/* LEGAL */
Route::get('/cgu', 'LegalController@cgu')->name('legal.cgu');
Route::get('/cgu/validate', 'LegalController@validation')->name('legal.validate');
Route::get('/cgu/validate/accepted', 'LegalController@acceptCGU')->name('accept_cgu');

/* ADMIN */
Route::get('/kbr-admin', 'Admin\AdminController@index')->name('admin');
Route::name('admin.')->group(function () {
    Route::resource('/kbr-admin/blog', 'Admin\AdminBlogController');
    Route::resource('/kbr-admin/childcare', 'Admin\AdminChildCareController');
    Route::resource('/kbr-admin/sheet', 'Admin\AdminSheetController');
    Route::resource('/kbr-admin/user', 'Admin\AdminUserController');
});
Route::get('/kbr-admin/sheet/create', 'Admin\AdminSheetController@create')->name('admin.sheet.create');

// Route::get('/kbr-admin/blog/articles', 'Admin\AdminBlogController@articles')->name('admin.blog.articles');
Route::resource('/kbr-admin/childcare', 'Admin\AdminChildCareController', ['names' => 'admin.childcare']);
Route::resource('/kbr-admin/network', 'Admin\AdminNetworkController', ['names' => 'admin.network']);
Route::resource('/kbr-admin/user', 'Admin\AdminUserController', ['names' => 'admin.user']);

app/Childcare.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class Childcare extends Model
{

    public $table = 'create_childcare';


    /* User qui poste l'annonce */
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function accepted_by()
    {
        $user = User::where('id', $this->accepted_by)->first();
        return $user;
    }

}

app/Http/Controllers/ChildcareController.php
<?php

namespace App\Http\Controllers;

use App\Childcare;
use App\Http\Requests\StoreChildcare;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;

class ChildcareController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('CguTrue');
        $this->middleware('profilUncomplet');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $friends = Auth::user()->friends();
        $auth_id = Auth::user()->id;

        if (count($friends) === 0) {
            $childcares = Childcare::where('user_id', '=', $auth_id)->get();
            return view('childcare.index', compact('childcares'));
        }

        $childcares = Childcare::whereIn('user_id', Auth::user()
            ->getFriendsIds())
            ->where('accepted_by', '=', null)
            ->orderBy('created_at', 'desc')
            ->get();

        return view('childcare.index', compact('childcares', 'date'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $id = Auth::user()->id;

        $childcares = User::find($id)->childcares;


        return view('childcare.create', compact('childcares'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreChildcare $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(StoreChildcare $request)
    {
        $childcare = new Childcare;
        $childcare->user_id = $request->user()->id;
        $childcare->children = $request->get('children');
        $childcare->begining = $request->get('begining');
        $childcare->end = $request->get('end');
        $childcare->day = $request->get('day');
        $childcare->location = $request->get('location');
        $childcare->age_range = $request->get('age_range');
        $childcare->description = $request->get('description');

        $childcare->save();

        return back()->with('message', 'Votre annonce a bien été mise en ligne');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $childcare = DB::table('create_childcare')->find($id);

        return view('childcare.edit', compact('id', 'childcare'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $childcare = Childcare::find($id);

        $childcare->children = $request->get('children');
        $childcare->begining = $request->get('begining');
        $childcare->end = $request->get('end');
        $childcare->day = $request->get('day');
        $childcare->location = $request->get('location');
        $childcare->age_range = $request->get('age_range');
        $childcare->description = $request->get('description');

        $childcare->save();

        $myneeds = Auth::user()->childcares;


        return Redirect::route('childcare.myneeds', compact('myneeds'))->with('message', "La garde a été modifiée avec succès");

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('create_childcare')
            ->delete($id);

        return back()->with('childcare_delete', 'Vous venez de supprimer une garde');
    }


    public function myNeeds()
    {
        $myneeds = Childcare::where('user_id', Auth::user()->id)->orderBy('created_at', 'desc')->get();
        return view('childcare.myneeds', compact('myneeds', 'date'));
    }

    public function myChildcares()
    {
        $mychildcares = Childcare::where('accepted_by', Auth::user()->id)->orderBy('created_at', 'desc')->get();

        return view('childcare.mychildcares', compact('mychildcares'));
    }

    /* Permet a un user de se proposer pour une garde */
    public function acceptChildcare($id)
    {
        Auth::user()->acceptChildcare($id);

        $message = "Garde en attente d'être validée, retrouvée là dans la partie";
        
        return back()->with('garde_accept', $message);
    }

    /* Valide le user qui se propose pour la garde */
    public function confirmChildcare($id)
    {
        Auth::user()->confirmChildcare($id);

        $childcare = Childcare::find($id);
        $accepted_by = $childcare->accepted_by()->name;

        $accepted = "Vous avez bien accepté $accepted_by pour la garde du $childcare->day";

        return back()->with('message', $accepted);
    }

    /* Refuse le user qui se propose pour la garde */
    public function refuseChildcare($id)
    {
        Auth::user()->refuseChildcare($id);

        $message = "Vous venez de refuser une garde, vous pouvez la retrouver dans la partie";

        return back()->with('childcare_refused', $message);
    }

    public function refuse($id)
    {
        Auth::user()->refuseChildcare($id);

        $message = "Vous avez bien supprimé la personne en charge de cette garde";

        return back()->with('childcare_refused', $message);
    }
}

resources/views/admin/childcare/edit.blade.php
@extends('admin.app')

@section('content')
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('admin.childcare.index') }}">Kambooroo Administration</a>
        </li>
        <li class="breadcrumb-item active">Gardes</li>
    </ol>
    <h1>Édition de la garde </h1>

            @if (session('message'))
                <div class="alert alert-success">
                    {{ session('message') }}
                </div>
            @endif
            <form method="post" action="{{ route('childcare.update', $id) }}" class="form-section">

                {{ csrf_field() }}
                {{ method_field('patch') }}

                <div class="form-group{{ $errors->has('children') ? ' has-error' : '' }}">
                    <label for="children" class="col-md-4 control-label">Nombre d'enfants</label>

                    <div class="col-md-6">
                        <select id="children" type="text" class="form-control" name="children" required
                                autofocus>
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                        </select>

                        @if ($errors->has('children'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('children') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('begining') ? ' has-error' : '' }}">
                    <label for="begining" class="col-md-4 control-label">Début</label>

                    <div class="col-md-6">
                        <input id="begining" type="text" class="form-control" name="begining"
                               value="{{ $childcare->begining }}" required autofocus>

                        @if ($errors->has('begining'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('begining') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('end') ? ' has-error' : '' }}">
                    <label for="end" class="col-md-4 control-label">Fin</label>

                    <div class="col-md-6">
                        <input id="end" type="text" class="form-control" name="end" value="{{ $childcare->end }}"
                               required autofocus>

                        @if ($errors->has('end'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('ennd') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('age_range') ? ' has-error' : '' }}">
                    <label for="age_range" class="col-md-4 control-label">Tranche d'âge</label>

                    <div class="col-md-6">
                        <select id="age_range" type="text" class="form-control" name="age_range" required
                                autofocus>
                            <option>Nouveau né (0 - 10 mois)</option>
                            <option>Nourrisson (10 mois - 2 ans)</option>
                            <option>Petit enfant (2 ans - 6 ans)</option>

                        </select>

                        @if ($errors->has('age_range'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('age_range') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('day') ? ' has-error' : '' }}">
                    <label for="day" class="col-md-4 control-label">Jour</label>

                    <div class="col-md-6">
                        <input id="day" type="text" class="form-control" name="day" value="{{ $childcare->day }}"
                               required autofocus>

                        @if ($errors->has('day'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('day') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('location') ? ' has-error' : '' }}">
                    <label for="location" class="col-md-4 control-label">Localisation</label>

                    <div class="col-md-6">
                        <input id="location" type="text" class="form-control" name="location"
                               value="{{ $childcare->location }}" required autofocus>

                        @if ($errors->has('location'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('location') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="">Description</label>
                        <textarea class="form-control" rows="10" cols="auto" placeholder="Prénom des enfants à garder, âge, consignes particulières..." id="description" name="description" required>{{ $childcare->description }}</textarea>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6 col-md-offset-4">
                        <button type="submit" class="btn btn-primary">
                            Publier
                        </button>
                    </div>
                </div>

            </form>

@endsection

resources/views/admin/childcare/index.blade.php
@extends('admin.app')

@section('content')
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('admin.childcare.index') }}">Kambooroo Administration</a>
        </li>
        <li class="breadcrumb-item active">Gardes</li>
    </ol>
                        <div class="panel-body">
                            @if (session('status'))
                                <div class="alert alert-success">
                                    {{ session('status') }}
                                </div>
                            @endif
                            <hr>
                            @if(count($childcares) > 0)

                                <table class="table table-striped table-responsive">
                                    <tr>
                                        <th>Liste des gardes</th>
                                        <th></th>
                                        <th></th>
                                    </tr>
                                    @foreach($childcares as $childcare)
                                        <tr>
                                            <td>Garde de {{$childcare->user->name}} du {{$childcare->day}} pour {{$childcare->age_range}} sur {{$childcare->location}}  </td>
                                            <td><a class="btn btn-primary" href="{{ route('admin.childcare.edit', $childcare->id)}}">Modifier</a></td>
                                            <td>
                                                <form action="{{ route('admin.childcare.destroy', $childcare->id)}}" method="POST">
                                                    {{ csrf_field() }}
                                                    {{ method_field('delete') }}
                                                    <button class="btn btn-danger">Supprimer</button>
                                                </form></td>
                                        </tr>
                                    @endforeach
                                </table>

                            @else
                                <p>Pas de garde pour le moment</p>
                            @endif
                        </div>
                        @endsection