routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/* REGISTER/LOGIN */
Auth::routes();
Route::get('{provider}', 'AuthSocialController@redirect')->where('provider', '(facebook|google)');
Route::get('{provider}/callback', 'AuthSocialController@callback')->where('provider', '(facebook|google)');
Route::get('/changePassword', 'HomeController@showChangePasswordForm');
Route::post('/changePassword', 'HomeController@changePassword')->name('changePassword');
Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser')->name('verify.user');
// Route::get('/verify/resend/', 'Auth\LoginController@verifyAccountReSendEmail')->name('verify.user.resend');

/* DASHBOARD */
Route::get('/home', 'HomeController@index')->name('home');

/* CONTACT */
Route::get('/contact', 'ContactController@show')->name('contact');
Route::post('/contact/send', 'ContactController@send')->name('contact.send');

/* USER */
Route::resource('/user', 'UserController');

/* NETWORK */
Route::get('/network/{slug}/Addfriend', 'NetworkController@getAdd')->name('addFriend');
Route::get('/network/{slug}/Acceptfriend', 'NetworkController@getAccept')->name('Acceptfriend');
Route::get('/network/search', 'NetworkController@searchcontact')->name('network.search');
Route::get('/network/{slug}/invitations', 'NetworkController@invitations');
Route::get('network/{slug}/delete', ['uses' => 'NetworkController@destroy', 'as' => 'network.delete']);
Route::post('network/search/result', 'NetworkController@search')->name('network.search.result');
Route::resource('/network', 'NetworkController');

/* BLOG */
Route::resource('/blog', 'BlogController');

/* WORKSHOP */
Route::resource('/workshop', 'WorkshopController');

/* ADVICE SHEET */
Route::resource('/sheet', 'AdviceSheetController');
Route::get('/sheet/pdf/{id}', 'AdviceSheetController@pdf')->name('sheet.pdf');

/* NOTIFICATIONS */
Route::resource('/notifications', 'NotificationsController');

/* CHILDCARE */
Route::get('/childcare/acceptchildcare/{id}', 'ChildcareController@acceptChildcare')->name('childcare.accept');
Route::get('/childcare/confirmchildcare/{id}', 'ChildcareController@confirmChildcare')->name('childcare.confirm');
Route::get('/childcare/refusechildcare/{id}', 'ChildcareController@refuseChildcare')->name('childcare.refuse');
Route::get('/childcare/refuse/{id}', 'ChildcareController@refuse')->name('childcare.refused');
Route::get('childcare/{id}/delete', ['uses' => 'ChildcareController@destroy', 'as' => 'childcare.delete']);
Route::get('/childcare/networkneeds', 'ChildcareController@networkNeeds')->name('childcare.networkneeds');
Route::get('/childcare/myneeds', 'ChildcareController@myNeeds')->name('childcare.myneeds');
Route::get('/childcare/mychildcares', 'ChildcareController@myChildcares')->name('childcare.mychildcares');
Route::resource('/childcare', 'ChildcareController');

/* LEGAL */
Route::get('/cgu', 'LegalController@cgu')->name('legal.cgu');
Route::get('/cgu/validate', 'LegalController@validation')->name('legal.validate');
Route::get('/cgu/validate/accepted', 'LegalController@acceptCGU')->name('accept_cgu');

/* ADMIN */
Route::get('/kbr-admin', 'Admin\AdminController@index')->name('admin');
Route::name('admin.')->group(function () {
    Route::resource('/kbr-admin/blog', 'Admin\AdminBlogController');
    Route::resource('/kbr-admin/childcare', 'Admin\AdminChildCareController');
    Route::resource('/kbr-admin/sheet', 'Admin\AdminSheetController');
    Route::resource('/kbr-admin/user', 'Admin\AdminUserController');
});
Route::get('/kbr-admin/sheet/create', 'Admin\AdminSheetController@create')->name('admin.sheet.create');

// Route::get('/kbr-admin/blog/articles', 'Admin\AdminBlogController@articles')->name('admin.blog.articles');
Route::resource('/kbr-admin/childcare', 'Admin\AdminChildCareController', ['names' => 'admin.childcare']);
Route::resource('/kbr-admin/network', 'Admin\AdminNetworkController', ['names' => 'admin.network']);
Route::resource('/kbr-admin/user', 'Admin\AdminUserController', ['names' => 'admin.user']);

resources/views/admin/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Administration</title>

    <!-- Styles -->
    <link href="{{ asset('css/admin.css') }}" rel="stylesheet">
</head>
<body class="fixed-nav sticky-footer bg-dark" id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="{{ route('admin') }}">Administration</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                <a class="nav-link" href="{{ route('admin') }}">
                    <i class="fa fa-fw fa-dashboard"></i>
                    <span class="nav-link-text">Dashboard</span>
                </a>
            </li>

            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                <a class="nav-link" href="{{ route('admin.user.index') }}">
                    <i class="fa fa-fw fa-users"></i>
                    <span class="nav-link-text">Utilisateur</span>
                </a>
            </li>

            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                <a class="nav-link" href="{{ route('admin.blog.index') }}">
                    <i class="fa fa-fw fa-newspaper-o"></i>
                    <span class="nav-link-text">Blog</span>
                </a>
            </li>


            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                <a class="nav-link" href="{{ route('admin.sheet.index') }}">
                    <i class="fa fa-fw fa-th"></i>
                    <span class="nav-link-text">Fiches conseils</span>
                </a>
            </li>

            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                <a class="nav-link" href="{{ route('admin.childcare.index') }}">
                    <i class="fa fa-fw fa-handshake-o"></i>
                    <span class="nav-link-text">Gardes</span>
                </a>
            </li>
        </ul>
        <ul class="navbar-nav sidenav-toggler">
            <li class="nav-item">
                <a class="nav-link text-center" id="sidenavToggler">
                    <i class="fa fa-fw fa-angle-left"></i>
                </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <!--
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-fw fa-envelope"></i>
                    <span class="d-lg-none">Messages
              <span class="badge badge-pill badge-primary">12 New</span>
            </span>
                    <span class="indicator text-primary d-none d-lg-block">
              <i class="fa fa-fw fa-circle"></i>
            </span>
                </a>
                <div class="dropdown-menu" aria-labelledby="messagesDropdown">
                    <h6 class="dropdown-header">New Messages:</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <strong>David Miller</strong>
                        <span class="small float-right text-muted">11:21 AM</span>
                        <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome! These messages clip off when they reach the end of the box so they don't overflow over to the sides!</div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <strong>Jane Smith</strong>
                        <span class="small float-right text-muted">11:21 AM</span>
                        <div class="dropdown-message small">I was wondering if you could meet for an appointment at 3:00 instead of 4:00. Thanks!</div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <strong>John Doe</strong>
                        <span class="small float-right text-muted">11:21 AM</span>
                        <div class="dropdown-message small">I've sent the final files over to you for review. When you're able to sign off of them let me know and we can discuss distribution.</div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item small" href="#">View all messages</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-fw fa-bell"></i>
                    <span class="d-lg-none">Alerts
              <span class="badge badge-pill badge-warning">6 New</span>
            </span>
                    <span class="indicator text-warning d-none d-lg-block">
              <i class="fa fa-fw fa-circle"></i>
            </span>
                </a>
                <div class="dropdown-menu" aria-labelledby="alertsDropdown">
                    <h6 class="dropdown-header">New Alerts:</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
              <span class="text-success">
                <strong>
                  <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
              </span>
                        <span class="small float-right text-muted">11:21 AM</span>
                        <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
              <span class="text-danger">
                <strong>
                  <i class="fa fa-long-arrow-down fa-fw"></i>Status Update</strong>
              </span>
                        <span class="small float-right text-muted">11:21 AM</span>
                        <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
              <span class="text-success">
                <strong>
                  <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
              </span>
                        <span class="small float-right text-muted">11:21 AM</span>
                        <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item small" href="#">View all alerts</a>
                </div>
            </li>
            <li class="nav-item">
                <form class="form-inline my-2 my-lg-0 mr-lg-2">
                    <div class="input-group">
                        <input class="form-control" type="text" placeholder="Search for...">
                        <span class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fa fa-search"></i>
                </button>
              </span>
                    </div>
                </form>
            </li>
            !-->
            <li class="nav-item">
                <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
                    <i class="fa fa-fw fa-sign-out"></i>Retour au site</a>
            </li>
        </ul>
    </div>
</nav>
<div class="content-wrapper">


    <div class="container-fluid">
        @yield('content')
    </div>
    <!-- /.container-fluid-->
    <!-- /.content-wrapper-->
    <footer class="sticky-footer">
        <div class="container">
            <div class="text-center">
                <small>Copyright © Kambooroo 2018</small>
            </div>
        </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fa fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Revenir sur le site</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Etes-vous certain de vouloir revenir sur le site Kambooroo ?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
                    <a class="btn btn-primary" href="{{ route('home') }}">Quitter l'administration</a>
                </div>
            </div>
        </div>
    </div>
    <script src="{{asset('assets/js/admin-vendor.js')}}"></script>
    <script src="{{asset('assets/js/admin-sb.js')}}"></script>

</div>
</body>
</html>

resources/views/admin/index.blade.php
@extends('admin.app')

@section('content')

    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Accueil</li>
    </ol>
    <!-- Icon Cards-->
    <div class="row">
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-primary o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fa fa-fw fa-users"></i>
                    </div>
                    <div class="mr-5">{{ $users }} utilisateurs</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="{{ route('admin.user.index') }}">
                    <span class="float-left">Gérer</span>
                    <span class="float-right">
                <i class="fa fa-angle-right"></i>
              </span>
                </a>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-warning o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fa fa-fw fa-newspaper-o"></i>
                    </div>
                    <div class="mr-5">{{ $articles }} articles de blog</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="{{ route('admin.blog.index') }}">
                    <span class="float-left">Gérer</span>
                    <span class="float-right">
                <i class="fa fa-angle-right"></i>
              </span>
                </a>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-success o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fa fa-fw fa-th"></i>
                    </div>
                    <div class="mr-5">{{ $sheets }} fiches conseils</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="{{ route('admin.sheet.index') }}">
                    <span class="float-left">Gérer</span>
                    <span class="float-right">
                <i class="fa fa-angle-right"></i>
              </span>
                </a>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-danger o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fa fa-fw fa-handshake-o"></i>
                    </div>
                    <div class="mr-5">{{ $childcares }} gardes</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="{{ route('admin.childcare.index') }}">
                    <span class="float-left">Gérer</span>
                    <span class="float-right">
                <i class="fa fa-angle-right"></i>
              </span>
                </a>
            </div>
        </div>
    </div>


@endsection