routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/* REGISTER/LOGIN */
Auth::routes();
Route::get('{provider}', 'AuthSocialController@redirect')->where('provider', '(facebook|google)');
Route::get('{provider}/callback', 'AuthSocialController@callback')->where('provider', '(facebook|google)');
Route::get('/changePassword', 'HomeController@showChangePasswordForm');
Route::post('/changePassword', 'HomeController@changePassword')->name('changePassword');
Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser')->name('verify.user');
// Route::get('/verify/resend/', 'Auth\LoginController@verifyAccountReSendEmail')->name('verify.user.resend');

/* DASHBOARD */
Route::get('/home', 'HomeController@index')->name('home');

/* CONTACT */
Route::get('/contact', 'ContactController@show')->name('contact');
Route::post('/contact/send', 'ContactController@send')->name('contact.send');

/* USER */
Route::resource('/user', 'UserController');

/* NETWORK */
Route::get('/network/{slug}/Addfriend', 'NetworkController@getAdd')->name('addFriend');
Route::get('/network/{slug}/Acceptfriend', 'NetworkController@getAccept')->name('Acceptfriend');
Route::get('/network/search', 'NetworkController@searchcontact')->name('network.search');
Route::get('/network/{slug}/invitations', 'NetworkController@invitations');
Route::get('network/{slug}/delete', ['uses' => 'NetworkController@destroy', 'as' => 'network.delete']);
Route::post('network/search/result', 'NetworkController@search')->name('network.search.result');
Route::resource('/network', 'NetworkController');

/* BLOG */
Route::resource('/blog', 'BlogController');

/* WORKSHOP */
Route::resource('/workshop', 'WorkshopController');

/* ADVICE SHEET */
Route::resource('/sheet', 'AdviceSheetController');
Route::get('/sheet/pdf/{id}', 'AdviceSheetController@pdf')->name('sheet.pdf');

/* NOTIFICATIONS */
Route::resource('/notifications', 'NotificationsController');

/* CHILDCARE */
Route::get('/childcare/acceptchildcare/{id}', 'ChildcareController@acceptChildcare')->name('childcare.accept');
Route::get('/childcare/confirmchildcare/{id}', 'ChildcareController@confirmChildcare')->name('childcare.confirm');
Route::get('/childcare/refusechildcare/{id}', 'ChildcareController@refuseChildcare')->name('childcare.refuse');
Route::get('/childcare/refuse/{id}', 'ChildcareController@refuse')->name('childcare.refused');
Route::get('childcare/{id}/delete', ['uses' => 'ChildcareController@destroy', 'as' => 'childcare.delete']);
Route::get('/childcare/networkneeds', 'ChildcareController@networkNeeds')->name('childcare.networkneeds');
Route::get('/childcare/myneeds', 'ChildcareController@myNeeds')->name('childcare.myneeds');
Route::get('/childcare/mychildcares', 'ChildcareController@myChildcares')->name('childcare.mychildcares');
Route::resource('/childcare', 'ChildcareController');

/* LEGAL */
Route::get('/cgu', 'LegalController@cgu')->name('legal.cgu');
Route::get('/cgu/validate', 'LegalController@validation')->name('legal.validate');
Route::get('/cgu/validate/accepted', 'LegalController@acceptCGU')->name('accept_cgu');

/* ADMIN */
Route::get('/kbr-admin', 'Admin\AdminController@index')->name('admin');
Route::name('admin.')->group(function () {
    Route::resource('/kbr-admin/blog', 'Admin\AdminBlogController');
    Route::resource('/kbr-admin/childcare', 'Admin\AdminChildCareController');
    Route::resource('/kbr-admin/sheet', 'Admin\AdminSheetController');
    Route::resource('/kbr-admin/user', 'Admin\AdminUserController');
});
Route::get('/kbr-admin/sheet/create', 'Admin\AdminSheetController@create')->name('admin.sheet.create');

// Route::get('/kbr-admin/blog/articles', 'Admin\AdminBlogController@articles')->name('admin.blog.articles');
Route::resource('/kbr-admin/childcare', 'Admin\AdminChildCareController', ['names' => 'admin.childcare']);
Route::resource('/kbr-admin/network', 'Admin\AdminNetworkController', ['names' => 'admin.network']);
Route::resource('/kbr-admin/user', 'Admin\AdminUserController', ['names' => 'admin.user']);

app/Sheet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sheet extends Model
{
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function ageRange()
    {
        if ($this->age_range === 1) {
            return config('constants.age.0to3');
        }
        if ($this->age_range === 2) {
            return config('constants.age.3to6');
        }
        if ($this->age_range === 3) {
            return config('constants.age.6to12');
        }
        if ($this->age_range === 4) {
            return config('constants.age.12to14');
        }

    }
}

resources/views/sheet/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="site-content">
        <div class="container">
            <h3 class="content-title">Fiches Conseils</h3>
            <hr class="content-divider">
            <div class="text-center">
                <p>Astuces et informations pour les parents au quotidien.</p>
            </div>

            <!-- Cards
            <div class="row">

                <div class="col-md-4">
                    <div class="card text-center">
                        <img class="card-img-top" src="https://previews.123rf.com/images/famveldman/famveldman1512/famveldman151200063/49486322-children-playing-with-wooden-train-toddler-kid-and-baby-play-with-blocks-trains-and-cars-educational.jpg" alt="Card image cap">
                        <div class="card-body">
                            <div class="card-age mx-auto d-block">
                                2 - 3
                                <br>
                                <strong>ans</strong>
                            </div>
                            <div class="card-title">Fiche conseil n°1</div>
                            <div class="card-text">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                            </div>
                            <div class="card-button-group">
                                <a class="card-button-outline" href="#">Télécharger</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="card text-center">
                        <img class="card-img-top" src="https://www.todaysparent.com/wp-content/uploads/2017/09/unexpected-ways-outdoor-play-can-benefit-your-kid-1024x576-1499960820.jpg" alt="Card image cap">
                        <div class="card-body">
                            <div class="card-age mx-auto d-block">
                                2 - 3
                                <br>
                                <strong>ans</strong>
                            </div>
                            <div class="card-title">Fiche conseil n°1</div>
                            <div class="card-text">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                            </div>
                            <div class="card-button-group">
                                <a class="card-button-outline" href="#">Télécharger</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="card text-center">
                        <img class="card-img-top" src="https://previews.123rf.com/images/famveldman/famveldman1512/famveldman151200063/49486322-children-playing-with-wooden-train-toddler-kid-and-baby-play-with-blocks-trains-and-cars-educational.jpg" alt="Card image cap">
                        <div class="card-body">
                            <div class="card-age mx-auto d-block">
                                2 - 3
                                <br>
                                <strong>ans</strong>
                            </div>
                            <div class="card-title">Fiche conseil n°1</div>
                            <div class="card-text">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                            </div>
                            <div class="card-button-group">
                                <a class="card-button-outline" href="#">Télécharger</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="card text-center">
                        <img class="card-img-top" src="https://previews.123rf.com/images/famveldman/famveldman1512/famveldman151200063/49486322-children-playing-with-wooden-train-toddler-kid-and-baby-play-with-blocks-trains-and-cars-educational.jpg" alt="Card image cap">
                        <div class="card-body">
                            <div class="card-age mx-auto d-block">
                                2 - 3
                                <br>
                                <strong>ans</strong>
                            </div>
                            <div class="card-title">Fiche conseil n°1</div>
                            <div class="card-text">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                            </div>
                            <div class="card-button-group">
                                <a class="card-button-outline" href="#">Télécharger</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="card text-center">
                        <img class="card-img-top" src="https://previews.123rf.com/images/famveldman/famveldman1512/famveldman151200063/49486322-children-playing-with-wooden-train-toddler-kid-and-baby-play-with-blocks-trains-and-cars-educational.jpg" alt="Card image cap">
                        <div class="card-body">
                            <div class="card-age mx-auto d-block">
                                2 - 3
                                <br>
                                <strong>ans</strong>
                            </div>
                            <div class="card-title">Fiche conseil n°1</div>
                            <div class="card-text">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                            </div>
                            <div class="card-button-group">
                                <a class="card-button-outline" href="#">Télécharger</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div> -->

            @if(count($sheets) > 0)

                @foreach($sheets as $sheet)

                    <div class="well">
                        <img class="card-img-top" src="{{ asset('images/sheets/'.$sheet->image) }}" class="img-fluid">
                        <h1><a href="{{ asset('pdf/sheets/'. $sheet->file_name) }}">{{$sheet->title}}</a></h1>
                        <span>{{$sheet->ageRange()}}</span>
                        <p>{{$sheet->content}}</p>
                        <hr>
                        <small>{{$sheet->user->name}} |{{$sheet->created_at}}</small>
                    </div>

                @endforeach

            @else

                <p>Erreur: aucune fiche conseils disponible</p>

            @endif

        </div>
    </div>


@endsection

resources/views/sheet/show.blade.php
@extends('layouts.app')

@section('content')


    <div class="well">
        <a href="{{ route('sheet.index')}}" class="btn btn-default">Back to articles</a>
        <h1>{{$sheet->title}}</h1>
        <p>{{$sheet->content}}</p>
        <hr>
        <small>{{$sheet->created_at}}</small>
        <a href="{{ route('sheet.pdf',$sheet->id)}}" class="btn btn-primary">Télècharger l'article</a>
    </div>
@endsection