routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/* REGISTER/LOGIN */
Auth::routes();
Route::get('{provider}', 'AuthSocialController@redirect')->where('provider', '(facebook|google)');
Route::get('{provider}/callback', 'AuthSocialController@callback')->where('provider', '(facebook|google)');
Route::get('/changePassword', 'HomeController@showChangePasswordForm');
Route::post('/changePassword', 'HomeController@changePassword')->name('changePassword');
Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser')->name('verify.user');
// Route::get('/verify/resend/', 'Auth\LoginController@verifyAccountReSendEmail')->name('verify.user.resend');

/* DASHBOARD */
Route::get('/home', 'HomeController@index')->name('home');

/* CONTACT */
Route::get('/contact', 'ContactController@show')->name('contact');
Route::post('/contact/send', 'ContactController@send')->name('contact.send');

/* USER */
Route::resource('/user', 'UserController');

/* NETWORK */
Route::get('/network/{slug}/Addfriend', 'NetworkController@getAdd')->name('addFriend');
Route::get('/network/{slug}/Acceptfriend', 'NetworkController@getAccept')->name('Acceptfriend');
Route::get('/network/search', 'NetworkController@searchcontact')->name('network.search');
Route::get('/network/{slug}/invitations', 'NetworkController@invitations');
Route::get('network/{slug}/delete', ['uses' => 'NetworkController@destroy', 'as' => 'network.delete']);
Route::post('network/search/result', 'NetworkController@search')->name('network.search.result');
Route::resource('/network', 'NetworkController');

/* BLOG */
Route::resource('/blog', 'BlogController');

/* WORKSHOP */
Route::resource('/workshop', 'WorkshopController');

/* ADVICE SHEET */
Route::resource('/sheet', 'AdviceSheetController');
Route::get('/sheet/pdf/{id}', 'AdviceSheetController@pdf')->name('sheet.pdf');

/* NOTIFICATIONS */
Route::resource('/notifications', 'NotificationsController');

/* CHILDCARE */
Route::get('/childcare/acceptchildcare/{id}', 'ChildcareController@acceptChildcare')->name('childcare.accept');
Route::get('/childcare/confirmchildcare/{id}', 'ChildcareController@confirmChildcare')->name('childcare.confirm');
Route::get('/childcare/refusechildcare/{id}', 'ChildcareController@refuseChildcare')->name('childcare.refuse');
Route::get('/childcare/refuse/{id}', 'ChildcareController@refuse')->name('childcare.refused');
Route::get('childcare/{id}/delete', ['uses' => 'ChildcareController@destroy', 'as' => 'childcare.delete']);
Route::get('/childcare/networkneeds', 'ChildcareController@networkNeeds')->name('childcare.networkneeds');
Route::get('/childcare/myneeds', 'ChildcareController@myNeeds')->name('childcare.myneeds');
Route::get('/childcare/mychildcares', 'ChildcareController@myChildcares')->name('childcare.mychildcares');
Route::resource('/childcare', 'ChildcareController');

/* LEGAL */
Route::get('/cgu', 'LegalController@cgu')->name('legal.cgu');
Route::get('/cgu/validate', 'LegalController@validation')->name('legal.validate');
Route::get('/cgu/validate/accepted', 'LegalController@acceptCGU')->name('accept_cgu');

/* ADMIN */
Route::get('/kbr-admin', 'Admin\AdminController@index')->name('admin');
Route::name('admin.')->group(function () {
    Route::resource('/kbr-admin/blog', 'Admin\AdminBlogController');
    Route::resource('/kbr-admin/childcare', 'Admin\AdminChildCareController');
    Route::resource('/kbr-admin/sheet', 'Admin\AdminSheetController');
    Route::resource('/kbr-admin/user', 'Admin\AdminUserController');
});
Route::get('/kbr-admin/sheet/create', 'Admin\AdminSheetController@create')->name('admin.sheet.create');

// Route::get('/kbr-admin/blog/articles', 'Admin\AdminBlogController@articles')->name('admin.blog.articles');
Route::resource('/kbr-admin/childcare', 'Admin\AdminChildCareController', ['names' => 'admin.childcare']);
Route::resource('/kbr-admin/network', 'Admin\AdminNetworkController', ['names' => 'admin.network']);
Route::resource('/kbr-admin/user', 'Admin\AdminUserController', ['names' => 'admin.user']);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'firstname', 'lastname', 'phone', 'postal', 'city', 'slug', 'cgu', 'image_name', 'facebook_id', 'google_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function friendsOfMine()

    {

        return $this->belongsToMany('App\user', 'friendship', 'user_id', 'friend_id');

    }

    public function friendOf()

    {

        return $this->belongsToMany('App\user', 'friendship', 'friend_id', 'user_id');

    }


    //la fonction qui gere le pivot
    public function friends()

    {

        return $this->friendsOfMine()->wherePivot('accepted', true)->get()->

        merge($this->friendOf()->wherePivot('accepted', true)->get());

    }


    //demande d'amis
    public function friendRequests()

    {

        return $this->friendsOfMine()->wherePivot('accepted', false)->get();

    }

    //demande d'amis en attente
    public function friendRequestsPending()

    {

        return $this->friendOf()->wherePivot('accepted', false)->get();

    }

    // comme demande d'amis en attente
    public function hasFriendRequestPending($user)

    {

        return (bool)$this->friendRequestsPending()->where('id', $user->id)->count();

    }

    // demande d'amis reçu
    public function hasFriendRequestReceived($user)

    {

        return (bool)$this->friendRequests()->where('id', $user->id)->count();

    }

    // Ajout ami
    public function addFriend($user)

    {

        $this->friendOf()->attach($user->id);

    }

    // Accept invitation

    public function acceptFriendRequest($user)

    {

        $this->friendRequests()->where('id', $user->id)->first()->pivot->update([

            'accepted' => true,

        ]);

    }

    public function refuseFriendRequest($user)
    {

    }

    // Est ami avec

    public function isFriendsWith($user)

    {

        return (bool)$this->friends()->where('id', $user->id)->count();

    }


    /* Notifications */
    public function getNotificationsMessage($type)
    {
        if ($type == "App\Notifications\NewNetworkInvitation") {
            return "souhaite rejoindre votre réseau.";
        } elseif ($type == "App\Notifications\NewChildCare") {
            return "vient de poster une demande de childcare.";
        } else {
            return false;
        }
    }

    public function getNotificationsLink($type)
    {
        if ($type == "App\Notifications\NewNetworkInvitation") {
            return route('network.index');
        } elseif ($type == "App\Notifications\NewChildCare") {
            return route('childcare.index');
        } else {
            return false;
        }


    }

    public function isAdmin()
    {
        return (bool)$this->admin;
    }

    public function cgu()
    {
        return (bool)$this->cgu;
    }


    public function verifyUser()
    {
        return $this->hasOne('App\VerifyUser');
    }


    public function avatar()
    {
        if (substr($this->image_name, 0, 4) === "http") {
            $imageLink = $this->image_name;
            return $imageLink;
        } else {
            $imageLink = asset('images/avatars/' . $this->image_name . '');
            return $imageLink;
        }
    }


    public function getFriendsIds()
    {

        $friendsIds = [];
        foreach ($this->friends() as $friend) {
            $friendsIds[] = $friend->id;
        }

        return $friendsIds;
    }

    public function childcares()
    {
        return $this->hasMany('App\Childcare');

    }

    public function childcareAccepted_by()
    {
        return $this->belongsTo('App\Childcare');
    }

    /* Permet à un user de proposer pour un garde */
    public function acceptChildcare($id)
    {
        DB::table('create_childcare')
            ->where('id', $id)
            ->update(['accepted_by' => Auth::user()->id]);
    }

    /* Valide le user qui se propose pour la garde */
    public function confirmChildcare($id)
    {
        DB::table('create_childcare')
            ->where('id', $id)
            ->update(['accepted' => true]);
    }

    /* Refuse le user qui se propose pour la garde */
    public function refuseChildcare($id)
    {
        DB::table('create_childcare')
            ->where('id', $id)
            ->update(
                ['accepted' => false,
                    'accepted_by' => null]
            );
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UpdateProfil;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;

class UserController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('CguTrue');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param $slug
     *
     * @return \Illuminate\Http\Response
     */
    public function show($userslug)
    {
        $user = User::where('slug', $userslug)->first();

        if (!$user) {
            return redirect()->route('home');
        }
        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        $user = User::where('slug', $slug)->first();
        if (substr($user->image_name, 0, 4) === "http") {
            $imageLink = $user->image_name;
        } else {
            $imageLink = asset('images/avatars/' . $user->image_name . '');
        }

        if (Auth::user()->slug !== $user->slug) {
            return redirect('/login');

        } else {
            return view('users.edit', compact('user', 'slug', 'imageLink'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProfil $request, $slug)
    {
        $passwordIsOk = password_verify($request->get('password'), Auth::user()->getAuthPassword());

        if ($passwordIsOk == true) {
            $user = User::where('slug', $slug)->first();
            // $user->name = $request->get('name');
            $user->email = $request->get('email');
            $user->phone = $request->get('phone');
            $user->city = $request->get('city');
            $user->postal = $request->get('postal');


            if ($request->hasFile('image')) {
                $imageName = time() . '.' . $request->image->getClientOriginalName();
                $request->image->move(public_path('images/avatars'), $imageName);
                $user->image_name = $imageName;
            }

            $user->update();

            return Redirect::back();

        } elseif (Auth::user()->password == []) {
            $user = User::where('slug', $slug)->first();
            //$user->name = $request->get('name');
            $user->email = $request->get('email');
            $user->phone = $request->get('phone');
            $user->city = $request->get('city');
            $user->postal = $request->get('postal');

            if ($request->hasFile('image')) {
                $imageName = time() . '.' . $request->image->getClientOriginalName();
                $request->image->move(public_path('images/avatars'), $imageName);
                $user->image_name = $imageName;
            }

            $user->update();

            return Redirect::back();

        } elseif

        ($passwordIsOk == false) {
            return Redirect::back()->withErrors(['Mauvais mot de passe']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/user/edit.blade.php
@extends('admin.app')


@section('content')

    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('admin.user.index') }}">Kambooroo Administration</a>
        </li>
        <li class="breadcrumb-item active">Utilisateurs</li>
    </ol>

    @if(session('message'))
        <div class='alert alert-success'>
            {{ session('message') }}
        </div>
    @endif

    <div class="site-content">
        <div class="container">
            <h3 class="content-title">PROFIL DE
                <strong class="content-strong">{{ $user->firstname }} {{ $user->lastname }}</strong></h3>
            <hr class="content-divider">

            <div class="content-form">
                <img class="rounded-circle" src="{{ $user->avatar() }}" alt="" width="150" height="150">
                <form enctype="multipart/form-data" method="post" action="{{ route('admin.user.update', $user->id) }}">
                    {{ csrf_field() }}
                    {{ method_field('patch') }}

                    <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }} text-center">
                        <label for="image" class="control-label">Photo de profil</label><br>
                        <input type="file" class="" name="image" id="image" value="{{ $user->image_name }}"/>
                        @if ($errors->has('image'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                        @endif
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group{{ $errors->has('firstname') ? ' has-error' : '' }}">
                                <label for="firstname" class="control-label">Prénom</label>
                                <input type="text" class="form-control" name="firstname" id="firstname" placeholder="Prénom" value="{{ $user->firstname }}" required/>
                                @if ($errors->has('fistname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('firstname') }}</strong>
                                    </span>
                                @endif
                            </div>

                        </div>

                        <div class="col-md-6">
                            <div class="form-group{{ $errors->has('lastname') ? ' has-error' : '' }}">
                                <label for="lastname" class="control-label">Nom</label>
                                <input type="text" class="form-control" name="lastname" id="lastname" value="{{ $user->lastname }}" required/>
                                @if ($errors->has('lastname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('lastname') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                <label for="email" class="control-label">Email</label>
                                <input type="email" class="form-control" name="email" id="email" value="{{ $user->email }}" required/>
                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group{{ $errors->has('postal') ? ' has-error' : '' }}">
                                <label for="postal" class="control-label">Code postal</label>
                                <input type="number" class="form-control" name="postal" id="postal" maxlength="5" placeholder="Code Postal" value="{{ $user->postal }}" required/>
                                @if ($errors->has('postal'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('postal') }}</strong>
                                    </span>
                                @endif
                            </div>

                        </div>

                        <div class="col-md-6">
                            <div class="form-group{{ $errors->has('city') ? ' has-error' : '' }}">
                                <label for="city" class="control-label">Ville</label>
                                <input type="text" class="form-control" name="city" id="city" value="{{ $user->city }}" required/>
                                @if ($errors->has('city'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('city') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="col-md-12">

                            <div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
                                <label for="phone" class="control-label">Téléphone</label>
                                <input type="text" class="form-control" name="phone" id="phone" placeholder="Téléphone" value="{{ $user->phone }}" required/>
                                @if ($errors->has('phone'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('phone') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary">Confirmer</button>


                </form>
            </div>

        </div>
    </div>




@endsection

resources/views/admin/user/index.blade.php
@extends('admin.app')

@section('content')
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('admin.user.index') }}">Kambooroo Administration</a>
        </li>
        <li class="breadcrumb-item active">Utilisateurs</li>
    </ol>


    <!-- Content -->
    <div class="panel-body">
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        <hr>
        @if(count($users) > 0)

            <table class="table table-striped table-responsive">
                <tr>
                    <th>Liste des utilisateurs</th>
                    <th></th>
                    <th></th>
                </tr>
                @foreach($users as $user)
                    <tr>
                        <td>{{$user->name}}</td>
                        <td><a class="btn btn-primary" href="{{ route('admin.user.edit', $user->id)}}">Modifier</a></td>
                        <td>
                            <form action="{{ route('admin.user.destroy', $user->id)}}" method="POST">
                                {{ csrf_field() }}
                                {{ method_field('delete') }}
                                <button class="btn btn-danger">Supprimer</button>
                            </form></td>
                    </tr>
                @endforeach
            </table>

        @else
            <p>Pas d'article pour le moment</p>
        @endif
    </div>
@endsection